meta_product_name: "UniTixHub"
meta_title: "UniTixHub"
meta_description: "Buy and Sell Tickets. Exclusively for Uni Students."
meta_image: "unitix-logo.png"                       # should exist in `app/assets/images/`
